const regularA = {
    nombre: "Regular A",
    descripcion: "Terminal Naranjal - Estación Central",
    color: "black",
    frecuencia: "Cada 15 minutos",
    precio: "S/. 3.20",
    puntos: [
        paraderos.par200.coordenadas,
        paraderos.par201.coordenadas,
        paraderos.par202.coordenadas,
        paraderos.par203.coordenadas,
        paraderos.par204.coordenadas,
        paraderos.par205.coordenadas,
        paraderos.par206.coordenadas,
        paraderos.par207.coordenadas,
        paraderos.par208.coordenadas,
        paraderos.par209.coordenadas,
        paraderos.par210.coordenadas,
        paraderos.par211.coordenadas,
        paraderos.par212.coordenadas,
        paraderos.par213.coordenadas,
        paraderos.par214.coordenadas,
        paraderos.par217.coordenadas
    ],
    paraderos: [
        paraderos.par200,
        paraderos.par201,
        paraderos.par202,
        paraderos.par203,
        paraderos.par204,
        paraderos.par205,
        paraderos.par206,
        paraderos.par207,
        paraderos.par208,
        paraderos.par209,
        paraderos.par210,
        paraderos.par211,
        paraderos.par212,
        paraderos.par213,
        paraderos.par214,
        paraderos.par217
    ]
};