const regularC = {
    nombre: "Regular C",
    descripcion: "Estación Ramón Castilla - Terminal Matellini",
    color: "black",
    frecuencia: "Cada 15 minutos",
    precio: "S/. 3.20",
    puntos: [
        paraderos.par211.coordenadas,
        paraderos.par212.coordenadas,
        paraderos.par213.coordenadas,
        paraderos.par214.coordenadas,
        paraderos.par217.coordenadas,
        paraderos.par218.coordenadas,
        paraderos.par219.coordenadas,
        paraderos.par220.coordenadas,
        paraderos.par221.coordenadas,
        paraderos.par222.coordenadas,
        paraderos.par223.coordenadas,
        paraderos.par224.coordenadas,
        paraderos.par225.coordenadas,
        paraderos.par226.coordenadas,
        paraderos.par227.coordenadas,
        paraderos.par228.coordenadas,
        paraderos.par229.coordenadas,
        paraderos.par230.coordenadas,
        paraderos.par231.coordenadas,
        paraderos.par232.coordenadas,
        paraderos.par233.coordenadas,
        paraderos.par234.coordenadas,
        paraderos.par235.coordenadas,
        paraderos.par236.coordenadas
    ],
    paraderos: [
        paraderos.par211,
        paraderos.par212,
        paraderos.par213,
        paraderos.par214,
        paraderos.par217,
        paraderos.par218,
        paraderos.par219,
        paraderos.par220,
        paraderos.par221,
        paraderos.par222,
        paraderos.par223,
        paraderos.par224,
        paraderos.par225,
        paraderos.par226,
        paraderos.par227,
        paraderos.par228,
        paraderos.par229,
        paraderos.par230,
        paraderos.par231,
        paraderos.par232,
        paraderos.par233,
        paraderos.par234,
        paraderos.par235,
        paraderos.par236
    ]
};