const regularB = {
    nombre: "Regular B",
    descripcion: "Estación Los Incas - Estación Plaza De Flores",
    color: "black",
    frecuencia: "Cada 15 minutos",
    precio: "S/. 3.20",
    puntos: [
        paraderos.par196.coordenadas,
        paraderos.par197.coordenadas,
        paraderos.par198.coordenadas,
        paraderos.par199.coordenadas,
        paraderos.par200.coordenadas,
        paraderos.par201.coordenadas,
        paraderos.par202.coordenadas,
        paraderos.par203.coordenadas,
        paraderos.par204.coordenadas,
        paraderos.par205.coordenadas,
        paraderos.par206.coordenadas,
        paraderos.par207.coordenadas,
        paraderos.par208.coordenadas,
        paraderos.par209.coordenadas,
        paraderos.par210.coordenadas,
        paraderos.par214_xd.coordenadas,
        paraderos.par216.coordenadas,
        paraderos.par217.coordenadas,
        paraderos.par218.coordenadas,
        paraderos.par219.coordenadas,
        paraderos.par220.coordenadas,
        paraderos.par221.coordenadas,
        paraderos.par222.coordenadas,
        paraderos.par223.coordenadas,
        paraderos.par224.coordenadas,
        paraderos.par225.coordenadas,
        paraderos.par226.coordenadas,
        paraderos.par227.coordenadas,
        paraderos.par228.coordenadas,
        paraderos.par229.coordenadas
    ],
    paraderos: [
        paraderos.par196,
        paraderos.par197,
        paraderos.par198,
        paraderos.par199,
        paraderos.par200,
        paraderos.par201,
        paraderos.par202,
        paraderos.par203,
        paraderos.par204,
        paraderos.par205,
        paraderos.par206,
        paraderos.par207,
        paraderos.par208,
        paraderos.par209,
        paraderos.par210,
        paraderos.par214_xd,
        paraderos.par216,
        paraderos.par217,
        paraderos.par218,
        paraderos.par219,
        paraderos.par220,
        paraderos.par221,
        paraderos.par222,
        paraderos.par223,
        paraderos.par224,
        paraderos.par225,
        paraderos.par226,
        paraderos.par227,
        paraderos.par228,
        paraderos.par229
    ]
};