const ruta2 = {
    nombre: "Ruta 2 - Norte",
    descripcion: "Conexión con Terminal Norte",
    color: "green",
    frecuencia: "Cada 15 minutos",
    precio: "$6.00",
    puntos: [
        paraderos.par101.coordenadas,
        paraderos.par102.coordenadas,
        paraderos.par103.coordenadas,
        paraderos.par104.coordenadas,
        paraderos.par105.coordenadas,
        paraderos.par35.coordenadas,
        paraderos.par106.coordenadas,
        paraderos.par107.coordenadas,
        paraderos.par108.coordenadas,
        paraderos.par109.coordenadas,
        paraderos.par110.coordenadas,
        paraderos.par111.coordenadas,
        paraderos.par112.coordenadas,
        paraderos.par113.coordenadas,
        paraderos.par114.coordenadas,
        paraderos.par115.coordenadas,
        paraderos.par116.coordenadas
    ],
    paraderos: [
        paraderos.par101,
        paraderos.par102,
        paraderos.par103,
        paraderos.par104,
        paraderos.par105,
        paraderos.par35,
        paraderos.par106,
        paraderos.par107,
        paraderos.par108,
        paraderos.par109,
        paraderos.par110,
        paraderos.par111,
        paraderos.par112,
        paraderos.par113,
        paraderos.par114,
        paraderos.par115,
        paraderos.par116
    ]
};